channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - argparse==1.4.0
  - cloudpickle==2.0.0
  - numpy==1.24.3
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - scipy==1.9.1
name: mlflow-env
